### ISSUE TITLE
kicad-db-lib not writing out parts

### ISSUE THREAD

**Issue by tb3000** [Projektanker/kicad-db-lib#10]
I have been trying to get kicad-db-lib to work – great approach btw, that’s exactly what’s needed (especially when you come from eagle) but no joy – it accepts all input, confirms OK at the end but does not write a library back to disk (nor updates an existing one).

I followed your github steps but maybe I am doing something wrong? Especially what do I need to have in “parts path” and how do I define output to go to “MyAtomicParts.lib”

Is there a way to import an existing lib that has e.g. OC_FARNELL (and other) fields already – and use kicad-db-lib thereafter?

**Comment by SebastianRumohr** [comment]
> Especially what do I need to have in “parts path” and how do I define output to go to  "MyAtomicParts.lib”

With the release of version 1.4.4, the README was revised and the explanation of the individual orders improved.

> Is there a way to import an existing lib that has e.g. OC_FARNELL (and other) fields already – and use kicad-db-lib thereafter?

No this is not supported. Feel free to join the project and implement this feature.
