### ISSUE TITLE
Add a item failed

### ISSUE THREAD

**Issue by Ian-HL** [Projektanker/kicad-db-lib#56]
Hi~
     A few days ago, my colleague found your great project . But when I try to write the same data as you have show in your ReadMe ,I found there always show a error message.  I use the symbols you have noticed ( https://gitlab.com/kicad/libraries/kicad-symbols ). 
    
![image](https://user-images.githubusercontent.com/13363533/150457534-3c08be1b-61ae-4815-af2c-89b144539247.png)
     
     So I run the project , found the code which lined in "\src\KiCadDbLib\Services\KiCad\LibraryWriter\KiCad6LibrarySymbolTemplateFactory.cs" , num 45
`var symbol = root.Childs
                .Where(child => child.Name == "symbol")
                .SingleOrDefault(symbol => symbol.Childs[0].Name == symbolInfo.ToString());`

I change it to this     
`var symbol = root.Childs
                .Where(child => child.Name == "symbol")
                .SingleOrDefault(symbol => symbol.Childs[0].Name == symbolInfo.Name.ToString());`

   the code works.  so I'm wondering is there a bug .

   If I was wrong ,sorry for my disturb.

**Comment by SebastianRumohr** [comment]
Thanks for using this tool.
I did a quick check. Indeed it's a bug. I'll fix it in the next couple days.

**Comment by SebastianRumohr** [comment]
Fixed with [version 2.0.3](https://github.com/Projektanker/kicad-db-lib/releases/tag/2.0.3)
