### ISSUE TITLE
Kicad6

### ISSUE THREAD

**Issue by gert-lauritsen** [Projektanker/kicad-db-lib#58]
It dosn't seeem to be able to import fra kicad 6 libery.

**Comment by SebastianRumohr** [comment]
Could you provide more information of the steps you did?

**Comment by gert-lauritsen** [comment]
I installed it, an it start fine, then I set path for my components and so on, but when I try to run build/import nothing comes in. What I think is that since the new library has the .kicad_sym, that it may not import it. I get an empty database, and that is it.

**Comment by SebastianRumohr** [comment]
> but when I try to run build/import nothing comes in. 

There is no build/import command. Do you mean build? Or do you mean import custom fields?

> I get an empty database, and that is it.

There is no database. What is empty? The output library?

**Comment by gert-lauritsen** [comment]
I have path setting like this:
C:\kicad\
c:\Program Files\KiCad\6.0\share\kicad\symbols\
c:\Program Files\KiCad\6.0\share\kicad\footprints\
C:\kicad\library

and when I press import there is a short message that it can't acess c:\user and the rest can't be seen. But it just dosn't import anything.

**Comment by SebastianRumohr** [comment]
It seems that the application is not able to create the directory for the settings to be saved.  
The settings are stored at `C:\<user>\AppData\Roaming\kicad-db-lib\settings.json`.  
Could you try running the application as administrator or create the directory by yourself?

**Comment by gert-lauritsen** [comment]
Doesn't make any different

**Comment by SebastianRumohr** [comment]
I can't reproduce the bug.  
Which version do you use?  
Could you please send me the content of the `settings.json` file mentioned earlier.
Could by any chance make a short video of what you did and post it here?

**Comment by gert-lauritsen** [comment]
{"CustomFields":[],"DatabasePath":"C:\\kicad\\","FootprintsPath":"c:\\Program Files\\KiCad\\6.0\\share\\kicad\\footprints\\","OutputPath":"C:\\kicad\\library","SymbolsPath":"c:\\Program Files\\KiCad\\6.0\\share\\kicad\\symbols\\"}

**Comment by mikhailmihalkov** [comment]
Good afternoon! Unable to convert libraries  gives an error... Trying to convert these
https://github.com/issus/altium-library

**Comment by SebastianRumohr** [comment]
> Good afternoon! Unable to convert libraries  gives an error... Trying to convert these
> https://github.com/issus/altium-library

The application is only compatible with KiCad libraries.

**Comment by SebastianRumohr** [comment]
Closed due to inactivity.
